name: Code Coverage

on: [push,pull_request]

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Add empty translation file
        run: |
          mkdir assets/translations -p
          touch assets/translations/empty.json
          echo {} >> assets/translations/empty.json
      - name: Generate coverage report
        run: go test --race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt